language: android

jdk:
 - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-23.0.2
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19
